apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ou64k2kp2-java-springboot
  janus-idp.io/tekton: ou64k2kp2-java-springboot
  backstage.io/kubernetes-id: ou64k2kp2-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ou64k2kp2-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
